import mongoose from "mongoose";

const UserSchema = new mongoose.Schema({
  _id: { type: String, required: true },
  email: { type: String, required: false },
  role: String,
  // cookie: String,
  userProfileUrl: { type: String, required: false },
  memberId: String,
  firstName: String,
  designation: String,
  lastName: String,
  userAgent: String,
  uninstalledAt: Date,
  installedAt: Date,
  uninstallReason: String,
  active: Boolean,
  invite: Boolean,
  status: String,
  accountId: String,
  officialLinkedInCompanyUrl: String,
  companies: [
    {
      companyId: String,
      isAuthorOfCompany: Boolean,
      officialLinkedInCompanyUrl: String,
      isPrimary: Boolean,
    },
  ],
  accessToken: String,
  accessTokenExpirationTimeStamp: Number,
  createdAt: Date,
  updatedAt: Date,
  crmId: String,
  lastFrontLike: Date,
  inviteType: String,
  inviteLink: String,
  linkForInvitedUser: String,
  profileImageLink: String,
  onBoardingComplete: { type: Boolean, required: false, default: false },
  verificationCode: String,
  verificationCodeExpires: Date,
  emailVerified: Boolean,
  lastPostsAligned: Date,
  shareLink: String,
  lastSeen: Date,
  cardToken: String,
  cardExpiryMonth: String,
  cardExpiryYear: String,
  thisMonthLikes: Number,
  lastMonthLikes: Number,
  thisMonthName: String,
  lastMonthName: String,
  percentageChange: String,
  lastLikeInsightsSyncDate: Date,
  lastProspectScrappedDate: Date,
  linkedUsersAccountIds: [String],
  latestBgExtensionVersion: String,
  installSource: { type: String, default: "Not Found" },
  utm_medium: { type: String, default: "Not Found" },
  utm_campaign: { type: String, default: "Not Found" },
  region: String,
  jobTitle: String,
  profileLanguage: String,
  lastProfileSyncDate: { type: Date, default: new Date() },
  lastReportDownloadedAt: Date,
  inviterName: String,
  companyOwner: String,
  companyName: String,
  isAuthorOfPage: Boolean,
  noOfContactsInAccount: String,
  noOfSignupsInAccount: String,
  paymentLink: String,
  secondAccountName: String,
  noOfContactsInSecondAccount: String,
  thirdAccountName: String,
  noOfContactsInThirdAccount: String,
  mixpanelDistinctId: String,
  isMixpanelAliasCreated: Boolean,
  lastFrontLikeDate: Date,
  onBoardingFailReason: String,
  thisMonthsDailyLikes: Number,
  thisMonthsDailyLikesDate: Date,
  totalLikes: Number,
  lifetimeLikesAccountLevel: Number,
  currentMonthLikesAccountLevel: Number,
  pendingInvitedUsers: Boolean,
  isFirstMessageShownToUser: Boolean,
  crmUrl: String,
  accountPlan: String,
  adminEnabled: { type: Boolean, default: true },
});

const Users = mongoose.model("Users", UserSchema, "users");

export default Users;
